@startuml
participant 企业微信主页面 as main
participant 通讯录 as contact
participant 添加成员页面 as add_member
participant 添加部门页面 as add_department

main -> contact:进入通讯录
main -> add_member:点击添加成员按钮
add_member ->contact:1.填写成员信息 \n2.点击保存
contact -> add_department:点击添加部门按钮
add_department -> contact:1.添加部门名称 \n2.选择所属部门 \n3.点击保存

@enduml